### ISSUE TITLE
Doesn't work with SimpliSafe 3?

### ISSUE THREAD

**Issue by Stuart-Richards** [fholgado/homebridge-simplisafe-security-system#5]
I have a brand new SimpliSafe 3 system. In Homekit it looks like it's working and there's no error messages that I can see but it fails to actually control the SimpliSafe system at all even though it thinks it is.

**Comment by enriquecaballero** [comment]
+1

**Comment by chowielin** [comment]
All, I had the same issue. I just got a brand new SS 3 system and it didn't work (for now obvious reasons after looking at the code!). Anyways, I implemented it here: https://github.com/chowielin/homebridge-simplisafe-security-system
Will file a PR.
So far it's working for me with Apple Homekit running Homebridge in a Docker container on a QNAP NAS. Please let me know if it works for you.

**Comment by enriquecaballero** [comment]
Is it published on `npm`? Homebridge can't seem to find it.

**Comment by enriquecaballero** [comment]
@chowielin Awesome!!!

**Comment by chowielin** [comment]
No NPM package published yet. In install.sh, add:
npm install -g git+https://github.com/chowielin/homebridge-simplisafe-security-system.git

**Comment by Stuart-Richards** [comment]
@chowielin  Thank you! I haven't gotten it to work, but I think it's me not your update. I don't understand how to actually install the update you've added. I think when I try and install I'm still just getting the fholgado version. I don't understand your instructions to add to install.sh. I can't find any install.sh file?

**Comment by enriquecaballero** [comment]
@chowielin I have it working on my instance of Homebridge. It generally works fine, but every now and then it gets stuck on "Updating" leading to "No Response", but when I reopen the Home app it works. 
The error I constantly get is:
```
[2018-4-10 10:06:31] [Alarm System] getting alarm state: error
```

**Comment by chowielin** [comment]
@enriquecaballero Ok I am getting a similar issue. I thought I was handling AWAY_COUNT state but I can check. But I also suspect that it hangs because the API token that is from SS is expired so the calls are always failing and maybe that causes the hanging. I need to do some authCheck URL call and reacquire a new token if that authCheck fails. Let me try to fix that.

**Comment by enriquecaballero** [comment]
@chowielin Let me know if you try anything and I can test on my end.

**Comment by Stuart-Richards** [comment]
@chowielin OK, please excuse my noobness. I have it working now. I had an issue with the npm cache that was preventing it installing. I've never installed something to npm using that method before and it completely threw me off! Once I cleared that cache out and fixed a permission issue it installed OK. So, thank you again for working on this. It's working for me! You're awesome. I'll let you know if I encounter the same issues with the AWAY_COUNT. Happy to provide any other logs etc.

**Comment by chowielin** [comment]
@enriquecaballero @Stuart-Richards Ok I pushed some more changes to add more logging in case of errors and also to do an authCheck to see if token is still valid, else refresh it. I will test this out myself but please let me know any errors or logs you see.
@Stuart-Richards Yeaup never have installed an npm pkg from git myself but it worked!

**Comment by enriquecaballero** [comment]
@chowielin Alright, just restarted my container -- and while it works most of the time, I still see this:
```
[2018-4-10 14:05:32] [Alarm System] getting alarm state: error
[2018-4-10 14:05:32] [Alarm System] Could not resolve SS state: error to Homekit security system state
```

**Comment by enriquecaballero** [comment]
Might not be an error on your end though -- not sure.

**Comment by enriquecaballero** [comment]
@chowielin I'll report back if I experience any weird issues.

**Comment by chowielin** [comment]
@enriquecaballero Ok yeah I have seen that the get alarm REST API for ss3 APIs was returning "error" sometimes on start up. I couldn't figure that out. But despite this, is it still hanging for you in the Homekit app? or is the status able to show correctly?

**Comment by Stuart-Richards** [comment]
Status is showing perfectly for me!

**Comment by enriquecaballero** [comment]
@chowielin So far so good. I'll test it today and get back to you tomorrow.

**Comment by chowielin** [comment]
@enriquecaballero @Stuart-Richards If you can check specifically for the token reacquire case. So I saw SS3 gives a token back upon login that is valid for one hour. However, I noticed that if it isn't used to make calls, then it eventually times out even before the hour. In either case, I had added logic to try to get a new token after 90% of one hour is up OR the authCheck REST call fails.

So, if authCheck passed, but 90% of one hour has elapsed since the token was acquired, then you should see this in the logs:
**"Auth check passed, but token is about to expire so acquiring new token"**

If authCheck failed, then token isn't valid so you should see this in the logs:
**"Auth check failed so acquiring new token"**

**Comment by enriquecaballero** [comment]
@chowielin Will do.

**Comment by enriquecaballero** [comment]
@chowielin Okay, so update -- it shows Updating to No Response after getting:
```
[2018-4-10 15:44:38] [Alarm System] Auth check failed so acquiring new token
```
It works when I retry; positive is that it no longer blocks my other Homebridge devices from getting updated.

**Comment by enriquecaballero** [comment]
Also, keep getting:
```
[2018-4-10 16:01:24] [Alarm System] Could not resolve SS state: error to Homekit security system state
```
every now and then.

**Comment by chowielin** [comment]
@enriquecaballero ok it seems that the API might have a race condition. Getting the token and then immediately getting alarm state seems to be going thru but the state value is 'error'. Perhaps I'll add some retry logic after some pausing, like in a timeout.

**Comment by chowielin** [comment]
@enriquecaballero ok could you try again. I found the race condition. I was setting the HTTP auth headers BEFORE reacquiring token, so new token would be fetched, but old expired token was still being used which explains why refreshing homekit app again works as the new token is then used at that point,

**Comment by enriquecaballero** [comment]
@chowielin On it.

**Comment by enriquecaballero** [comment]
@chowielin Just restarted my container. I'll update within in an hour.

**Comment by chowielin** [comment]
@enriquecaballero Sorry. I think there are still issues.. I still think there is an issue after my own testing. Getting the no response like you are when new token acquired. I’ve narrowed it down to an issue with two tokens being acquired and the same time and stepping in each other. I noticed that Homekit is asking the alarm system for both current state and target same at the same exact time, thereby triggering two parallel calls to reacquire tokens. Going to try making it so that only one token is acquired.

**Comment by chowielin** [comment]
@enriquecaballero Ok i added some logic to make it so that there will only ever be one token reacquire. Any other one will just wait for that and return. Btw, I still get the "error" for the alarm state so the retry logic kicks in to make the same get alarm state call again and it seems to work. Seems to be a quirk with the SS3 APIs. I can't test this right now, but will tonight :)

**Comment by enriquecaballero** [comment]
@chowielin Just restarted my container again. I'll let you know if I run into anything.

**Comment by enriquecaballero** [comment]
@chowielin So far so good -- auth check failed, acquired a new token, and status was correctly shown in the Home app. I'll keep you posted.

**Comment by chowielin** [comment]
@enriquecaballero cool. thanks for trying it out. I will also check later tonight.

**Comment by enriquecaballero** [comment]
@chowielin Yeah, no problem. Good work!

**Comment by PoppyS33d** [comment]
Hey all, I know this hasn't been updated in a while, but I'm having issues with HomeBridge and SS3 on my Mac. I'm hoping that groupthink can help solve this.

I cannot control the Alarm status from the Home app. The Alarm stats reflects its current status (Home, Away, Off) accurately in the Home app, but actually trying to change it doesn't work, despite the app initially saying it did. In the Homebridge logs, I see this:

In this scenario, my SS3 is set to "Home" already, and I'm trying to turn it OFF from the Home app on my iPhone X. 

<img width="640" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/39997942/41054965-c911757e-6974-11e8-9d1e-e64a4c3d2d97.png">


Even more frustratingly, if I use the actual SimpliSafe app to change the status of the Alarm (from e.g. Home, to "OFF"),  I get completely kicked out of the Home app's ability to control my Nest thermostats or SimpliSafe. I just get "No Response" from any devices using HomeBridge. I'm not even sure what I did to fix it the first time. Either way, super frustrating!

Any ideas? Thank you!

**Comment by enriquecaballero** [comment]
@PoppyS33d How are you running Homebridge? Natively or through Docker?

**Comment by enriquecaballero** [comment]
@PoppyS33d Also, are you paying for the $25 _interactive_ version of SimpliSafe?

**Comment by PoppyS33d** [comment]
I'm running it natively I'm guessing. I've never tried running it any other way, and I've used it for my LiftMaster garage door, my Nest thermostats and Protects, the old SimpliSafe 2 etc. 

Yes, I'm using the interactive version of SimpliSafe, which is how I was able to control my SimpliSafe2 just fine. 

I also updated my post above to list a further side-effect/issue I have, too.

**Comment by enriquecaballero** [comment]
How are you installing this plugin?

**Comment by enriquecaballero** [comment]
I have `npm install --unsafe-perm git+https://github.com/chowielin/homebridge-simplisafe-security-system.git` in my startup script.

**Comment by PoppyS33d** [comment]
I installed the plugin by typing: 

npm install -g homebridge-simplisafe-security-system

as the instructions told me to do. Then I modified the config.json to have my credentials.

**Comment by enriquecaballero** [comment]
I don't think that will work with the modified SS3 version of this plugin as I don't think it's been released to npm yet. Try installing it by:
```
npm install -g git+https://github.com/chowielin/homebridge-simplisafe-security-system.git
```

**Comment by PoppyS33d** [comment]
OK I typed that command, - do I need to remove anything else or do anything else? I still have the original command I mentioned installed, and then a .plist in my LaunchAgents folder to auto-launch HomeBridge.

I'm just rebooting the Mac now to see if it works...

**Comment by enriquecaballero** [comment]
Well, you need to uninstall the original install and then run the command I provided.

**Comment by PoppyS33d** [comment]
I just ran:

npm install -g git+https://github.com/chowielin/homebridge-simplisafe-security-system.git 

 - then rebooted (without uninstalling the original install), and it works!!!!! 

I then uninstalled the original command, re-ran the git command, and it still works. 

Fantastic!  

THANK YOU.

**Comment by PoppyS33d** [comment]
I wish I'd realized you had to do that - I saw that install referenced a couple of months ago, but figured it was old news. 

*sigh*

Thank you again, and to Chowie for a super-useful HomeBridge plugin!

**Comment by chowielin** [comment]
@enriquecaballero
Thanks for the support handling! Another happy customer 😏

**Comment by mtcjmmy** [comment]
anybody getting errors trying to install this ? pulling my hair out 

npm install -g git+https://github.com/chowielin/homebridge-simplisafe-security-system.git

**Comment by chowielin** [comment]
@mtcjmmy Could you be more specific? What errors are you getting? You are you running Homebridge with this right?

**Comment by mtcjmmy** [comment]
i was trying to install on a raspberry pi

**Comment by mtcjmmy** [comment]
got it installed on my mac but just cant get the config.json right with all my other plugins

**Comment by chowielin** [comment]
@mtcjmmy Did you add something like this in your config.json (look at the sample-config.json in this repo):

  "accessories": [
{
  "accessory": "Homebridge-SimpliSafe",
  "name": "Alarm System",
  "auth": {
    "username": "user@domain.com",
    "password": "password"
  }
}
  ]

**Comment by mtcjmmy** [comment]
Got it all working thanks for the reply and the plugin works great

**Comment by Tiger519** [comment]
@chowielin Just adding my thanks for fixing this. Installed your version of the plugin and all is working fine!

**Comment by krazyflipj** [comment]
@chowielin for some reason, I started getting a failed 502 gateway error and failed to aquire new token. Anyone else?

**Comment by tjenvy** [comment]
I installed everything fine on my system.  Then this morning I added an extra code to my json file for a new switch.  the moment i did that, all hell broke loose.  I corrected my config back to the original.  Same issue happening.   Uninstalled home bridge, all assets, you name it.  re-installed everything, made a clean son config file just like before,  Still not working.  I just get this each time I open the home app.  (in terminal)

[3/23/2019, 3:56:50 PM] [Alarm System] Getting current state
[3/23/2019, 3:56:51 PM] [Alarm System] Getting target state
[3/23/2019, 4:05:59 PM] [Alarm System] Getting current state
[3/23/2019, 4:05:59 PM] [Alarm System] Getting target state

Current config  
macOS 10.11.6 (max version)
home bridge version  0.4.46
latest instal via npm install -g homebridge-simplisafe-security-system
u/p correct 


I have tired everything under the sun.  any ideas?  

conversely, I can use customer written "siri shortcuts" that work fine. but damn are they slow.  They use the same net-communication with the 25.00 package as this does.   So the system can communicate without issue.

**Comment by chowielin** [comment]
@krazyflipj I haven't seen that for my Simplisafe account. It was working before?

**Comment by krazyflipj** [comment]
@chowielin disregard. I think it was an issue with SimpliSafe website. All good now.

**Comment by kk0201** [comment]
@chowielin Not able to install on raspberry pi, after upgrading to new simplisafe. 

pi@raspberrypi:~ $ sudo npm install -g git+https://github.com/chowielin/homebridge-simplisafe-security-system.git
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/chowielin/homebridge-simplisafe-security-system.git /root/.npm/_cacache/tmp/git-clone-1c9b03b7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1c9b03b7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-25T00_39_14_161Z-debug.log

**Comment by chowielin** [comment]
@kk0201 That looks like an NPM error unrelated to the actual simplisafe git repo. I have never tried to install on a Raspberry pi.

**Comment by kk0201** [comment]
@chowielin Thanks, I was able to install it after downgrading NMP

**Comment by kk0201** [comment]
@chowielin 

I keep getting this error. Tried changing passwords multiple times. Logged out of app on all mobiles and updated password, but I still get this token error. 

Appreciate any help...  Thanks


0|homebrid | [4/2/2019, 4:13:05 AM] [SimpliSafe] Getting current state
0|homebrid | [4/2/2019, 4:13:06 AM] [SimpliSafe] SS3Client Auth check failed so acquiring new token. old token: *************mU4=
0|homebrid | [4/2/2019, 4:13:06 AM] [SimpliSafe] SS3Client: Failed to initToken: 429 - {"errorType":"UserBlockError","code":429,"message":"User has too many failed login attempts. Try again later."}
0|homebrid | [4/2/2019, 4:13:13 AM] [SimpliSafe] Getting target state
0|homebrid | [4/2/2019, 4:13:13 AM] [SimpliSafe] Getting current state
0|homebrid | [4/2/2019, 4:13:14 AM] [SimpliSafe] SS3Client Auth check failed so acquiring new token. old token: ********Yo4=
0|homebrid | [4/2/2019, 4:13:14 AM] [SimpliSafe] SS3Client: Failed to initToken: 429 - {"errorType":"UserBlockError","code":429,"message":"User has too many failed login attempts. Try again later."}
0|homebrid | [4/2/2019, 1:26:13 PM] [SimpliSafe] Getting target state
0|homebrid | [4/2/2019, 1:26:13 PM] [SimpliSafe] Getting current state
0|homebrid | [4/2/2019, 1:26:13 PM] [SimpliSafe] SS3Client Auth check failed so acquiring new token. old token: ********4=
0|homebrid | [4/2/2019, 1:26:13 PM] [SimpliSafe] SS3Client: Failed to initToken: 429 - {"errorType":"UserBlockError","code":429,"message":"User has too many failed login attempts. Try again later."}
0|homebrid | [4/2/2019, 5:24:21 PM] [SimpliSafe] Getting target state
0|homebrid | [4/2/2019, 5:24:21 PM] [SimpliSafe] Getting current state
0|homebrid | [4/2/2019, 5:24:21 PM] [SimpliSafe] SS3Client Auth check failed so acquiring new token. old token:  *********mU4=
0|homebrid | [4/2/2019, 5:24:21 PM] [SimpliSafe] SS3Client: Failed to initToken: 429 - {"errorType":"UserBlockError","code":429,"message":"User has too many failed login attempts. Try again later."}

**Comment by chowielin** [comment]
@kk0201 Wonder if your account is now locked out due to the numerous invalid login attempts. Are you able to log into the Simplisafe web console? Maybe give it some time for things to reset and make sure your password is valid.

**Comment by krazyflipj** [comment]
![CDB5B635-6633-4216-82AD-666F802C732C](https://user-images.githubusercontent.com/10282165/61990307-d317a780-aff2-11e9-9950-31dcc4dd3286.png)
@chowielin any chance to fix this minor issue on IOS13? Looks normal once you select alarm mode
